<a href="https://colab.research.google.com/github/GaeloHerrera/EDA-datos-CARS/blob/main/TP1/CARS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import adfuller

In [ ]:
data = pd.read_csv("COPY_CARS.csv")

In [ ]:
data.shape

(428, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      428 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    int64
 10  MPG_City     428 non-null    int64
 11  MPG_Highway  428 non-null    int64
 12  Weight       428 non-null    int64
 13  Wheelbase    428 non-null    int64
 14  Length       428 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 50.3+ KB

In [ ]:
data

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [ ]:
data["Make"].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'MINI', 'Mazda', 'Mercedes-Benz', 'Mercury',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [ ]:
marca = data["Make"].value_counts()
marca

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [ ]:
marca = data.query("Make == 'Toyota'")
marca

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
373,Toyota,Prius 4dr (gas/electric),Hybrid,Asia,Front,"$20,510","$18,926",1.5,4.0,110,59,51,2890,106,175
374,Toyota,Sequoia SR5,SUV,Asia,All,"$35,695","$31,827",4.7,8.0,240,14,17,5270,118,204
375,Toyota,4Runner SR5 V6,SUV,Asia,Front,"$27,710","$24,801",4.0,6.0,245,18,21,4035,110,189
376,Toyota,Highlander V6,SUV,Asia,All,"$27,930","$24,915",3.3,6.0,230,18,24,3935,107,185
377,Toyota,Land Cruiser,SUV,Asia,All,"$54,765","$47,986",4.7,8.0,325,13,17,5390,112,193
378,Toyota,RAV4,SUV,Asia,All,"$20,290","$18,553",2.4,4.0,161,22,27,3119,98,167
379,Toyota,Corolla CE 4dr,Sedan,Asia,Front,"$14,085","$13,065",1.8,4.0,130,32,40,2502,102,178
380,Toyota,Corolla S 4dr,Sedan,Asia,Front,"$15,030","$13,650",1.8,4.0,130,32,40,2524,102,178
381,Toyota,Corolla LE 4dr,Sedan,Asia,Front,"$15,295","$13,889",1.8,4.0,130,32,40,2524,102,178
382,Toyota,Echo 2dr manual,Sedan,Asia,Front,"$10,760","$10,144",1.5,4.0,108,35,43,2035,93,163
383,Toyota,Echo 2dr auto,Sedan,Asia,Front,"$11,560","$10,896",1.5,4.0,108,33,39,2085,93,163
384,Toyota,Echo 4dr,Sedan,Asia,Front,"$11,290","$10,642",1.5,4.0,108,35,43,2055,93,163
385,Toyota,Camry LE 4dr,Sedan,Asia,Front,"$19,560","$17,558",2.4,4.0,157,24,33,3086,107,189
386,Toyota,Camry LE V6 4dr,Sedan,Asia,Front,"$22,775","$20,325",3.0,6.0,210,21,29,3296,107,189
387,Toyota,Camry Solara SE 2dr,Sedan,Asia,Front,"$19,635","$17,722",2.4,4.0,157,24,33,3175,107,193
388,Toyota,Camry Solara SE V6 2dr,Sedan,Asia,Front,"$21,965","$19,819",3.3,6.0,225,20,29,3417,107,193
389,Toyota,Avalon XL 4dr,Sedan,Asia,Front,"$26,560","$23,693",3.0,6.0,210,21,29,3417,107,192
390,Toyota,Camry XLE V6 4dr,Sedan,Asia,Front,"$25,920","$23,125",3.0,6.0,210,21,29,3362,107,189
391,Toyota,Camry Solara SLE V6 2dr,Sedan,Asia,Front,"$26,510","$23,908",3.3,6.0,225,20,29,3439,107,193
392,Toyota,Avalon XLS 4dr,Sedan,Asia,Front,"$30,920","$27,271",3.0,6.0,210,21,29,3439,107,192
393,Toyota,Sienna CE,Sedan,Asia,Front,"$23,495","$21,198",3.3,6.0,230,19,27,4120,119,200
394,Toyota,Sienna XLE Limited,Sedan,Asia,Front,"$28,800","$25,690",3.3,6.0,230,19,27,4165,119,200
395,Toyota,Celica GT-S 2dr,Sports,Asia,Front,"$22,570","$20,363",1.8,4.0,180,24,33,2500,102,171
396,Toyota,MR2 Spyder convertible 2dr,Sports,Asia,Rear,"$25,130","$22,787",1.8,4.0,138,26,32,2195,97,153
397,Toyota,Tacoma,Truck,Asia,Rear,"$12,800","$11,879",2.4,4.0,142,22,27,2750,103,191
398,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190,16,18,3925,128,218
399,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,"$25,935","$23,520",3.4,6.0,190,14,17,4435,128,218
400,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130,29,36,2679,102,171

In [ ]:
data[data["Make"].isin(["Toyota", "Dodge"])]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
105,Dodge,Durango SLT,SUV,USA,All,"$32,235","$29,472",4.7,8.0,230,15,21,4987,119,201
106,Dodge,Neon SE 4dr,Sedan,USA,Front,"$13,670","$12,849",2.0,4.0,132,29,36,2581,105,174
107,Dodge,Neon SXT 4dr,Sedan,USA,Front,"$15,040","$14,086",2.0,4.0,132,29,36,2626,105,174
108,Dodge,Intrepid SE 4dr,Sedan,USA,Front,"$22,035","$20,502",2.7,6.0,200,21,29,3469,113,204
109,Dodge,Stratus SXT 4dr,Sedan,USA,Front,"$18,820","$17,512",2.4,4.0,150,21,28,3182,108,191
110,Dodge,Stratus SE 4dr,Sedan,USA,Front,"$20,220","$18,821",2.4,4.0,150,21,28,3175,108,191
111,Dodge,Intrepid ES 4dr,Sedan,USA,Front,"$24,885","$23,058",3.5,6.0,232,18,27,3487,113,204
112,Dodge,Caravan SE,Sedan,USA,Front,"$21,795","$20,508",2.4,4.0,150,20,26,3862,113,189
113,Dodge,Grand Caravan SXT,Sedan,USA,All,"$32,660","$29,812",3.8,6.0,215,18,25,4440,119,201
114,Dodge,Viper SRT-10 convertible 2dr,Sports,USA,Rear,"$81,795","$74,451",8.3,10.0,500,12,20,3410,99,176
115,Dodge,Dakota Regular Cab,Truck,USA,Rear,"$17,630","$16,264",3.7,6.0,210,16,22,3714,112,193
116,Dodge,Dakota Club Cab,Truck,USA,Rear,"$20,300","$18,670",3.7,6.0,210,16,22,3829,131,219
117,Dodge,Ram 1500 Regular Cab ST,Truck,USA,Rear,"$20,215","$18,076",3.7,6.0,215,16,21,4542,121,208
373,Toyota,Prius 4dr (gas/electric),Hybrid,Asia,Front,"$20,510","$18,926",1.5,4.0,110,59,51,2890,106,175
374,Toyota,Sequoia SR5,SUV,Asia,All,"$35,695","$31,827",4.7,8.0,240,14,17,5270,118,204
375,Toyota,4Runner SR5 V6,SUV,Asia,Front,"$27,710","$24,801",4.0,6.0,245,18,21,4035,110,189
376,Toyota,Highlander V6,SUV,Asia,All,"$27,930","$24,915",3.3,6.0,230,18,24,3935,107,185
377,Toyota,Land Cruiser,SUV,Asia,All,"$54,765","$47,986",4.7,8.0,325,13,17,5390,112,193
378,Toyota,RAV4,SUV,Asia,All,"$20,290","$18,553",2.4,4.0,161,22,27,3119,98,167
379,Toyota,Corolla CE 4dr,Sedan,Asia,Front,"$14,085","$13,065",1.8,4.0,130,32,40,2502,102,178
380,Toyota,Corolla S 4dr,Sedan,Asia,Front,"$15,030","$13,650",1.8,4.0,130,32,40,2524,102,178
381,Toyota,Corolla LE 4dr,Sedan,Asia,Front,"$15,295","$13,889",1.8,4.0,130,32,40,2524,102,178
382,Toyota,Echo 2dr manual,Sedan,Asia,Front,"$10,760","$10,144",1.5,4.0,108,35,43,2035,93,163
383,Toyota,Echo 2dr auto,Sedan,Asia,Front,"$11,560","$10,896",1.5,4.0,108,33,39,2085,93,163
384,Toyota,Echo 4dr,Sedan,Asia,Front,"$11,290","$10,642",1.5,4.0,108,35,43,2055,93,163
385,Toyota,Camry LE 4dr,Sedan,Asia,Front,"$19,560","$17,558",2.4,4.0,157,24,33,3086,107,189
386,Toyota,Camry LE V6 4dr,Sedan,Asia,Front,"$22,775","$20,325",3.0,6.0,210,21,29,3296,107,189
387,Toyota,Camry Solara SE 2dr,Sedan,Asia,Front,"$19,635","$17,722",2.4,4.0,157,24,33,3175,107,193
388,Toyota,Camry Solara SE V6 2dr,Sedan,Asia,Front,"$21,965","$19,819",3.3,6.0,225,20,29,3417,107,193
389,Toyota,Avalon XL 4dr,Sedan,Asia,Front,"$26,560","$23,693",3.0,6.0,210,21,29,3417,107,192
390,Toyota,Camry XLE V6 4dr,Sedan,Asia,Front,"$25,920","$23,125",3.0,6.0,210,21,29,3362,107,189
391,Toyota,Camry Solara SLE V6 2dr,Sedan,Asia,Front,"$26,510","$23,908",3.3,6.0,225,20,29,3439,107,193
392,Toyota,Avalon XLS 4dr,Sedan,Asia,Front,"$30,920","$27,271",3.0,6.0,210,21,29,3439,107,192
393,Toyota,Sienna CE,Sedan,Asia,Front,"$23,495","$21,198",3.3,6.0,230,19,27,4120,119,200
394,Toyota,Sienna XLE Limited,Sedan,Asia,Front,"$28,800","$25,690",3.3,6.0,230,19,27,4165,119,200
395,Toyota,Celica GT-S 2dr,Sports,Asia,Front,"$22,570","$20,363",1.8,4.0,180,24,33,2500,102,171
396,Toyota,MR2 Spyder convertible 2dr,Sports,Asia,Rear,"$25,130","$22,787",1.8,4.0,138,26,32,2195,97,153
397,Toyota,Tacoma,Truck,Asia,Rear,"$12,800","$11,879",2.4,4.0,142,22,27,2750,103,191
398,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190,16,18,3925,128,218
399,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,"$25,935","$23,520",3.4,6.0,190,14,17,4435,128,218
400,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130,29,36,2679,102,171

In [ ]:
data["Origin"].unique()
data["Origin"].value_counts()

Origin
Asia      158
USA       147
Europe    123
Name: count, dtype: int64

In [ ]:
data[["Make","Origin"]].value_counts()

Make           Origin
Toyota         Asia      28
Chevrolet      USA       27
Mercedes-Benz  Europe    26
Ford           USA       23
BMW            Europe    20
Audi           Europe    19
Honda          Asia      17
Nissan         Asia      17
Volkswagen     Europe    15
Chrysler       USA       15
Dodge          USA       13
Mitsubishi     Asia      13
Volvo          Europe    12
Jaguar         Europe    12
Hyundai        Asia      12
Subaru         Asia      11
Pontiac        USA       11
Mazda          Asia      11
Lexus          Asia      11
Kia            Asia      11
Buick          USA        9
Mercury        USA        9
Lincoln        USA        9
Saturn         USA        8
Cadillac       USA        8
Suzuki         Asia       8
Infiniti       Asia       8
GMC            USA        8
Acura          Asia       7
Porsche        Europe     7
Saab           Europe     7
Land Rover     Europe     3
Oldsmobile     USA        3
Jeep           USA        3
Scion          Asia       2
Isuzu          Asia       2
MINI           Europe     2
Hummer         USA        1
Name: count, dtype: int64

In [ ]:
data["Horsepower"].max()
data["Horsepower"].min()

73

In [ ]:
data[data["Horsepower"] == 500]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
114,Dodge,Viper SRT-10 convertible 2dr,Sports,USA,Rear,"$81,795","$74,451",8.3,10.0,500,12,20,3410,99,176

In [ ]:
data["Cylinders"].value_counts()

Cylinders
6.0     190
4.0     136
8.0      87
5.0       7
12.0      3
10.0      2
3.0       1
Name: count, dtype: int64

In [ ]:
data[(data["Make"]=="Audi") & (data["Horsepower"]>=200)]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220,18,25,4013,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450,15,22,4024,109,191
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220,18,25,4035,109,192
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179

In [ ]:
audi = data.query("Make == 'Audi'")
audi1 = audi.count()
audi1

Make           19
Model          19
Type           19
Origin         19
DriveTrain     19
MSRP           19
Invoice        19
EngineSize     19
Cylinders      19
Horsepower     19
MPG_City       19
MPG_Highway    19
Weight         19
Wheelbase      19
Length         19
dtype: int64

In [ ]:
 data["Type"].value_counts()
 # 1) ES MÁS ABUNDANTDE LA CARROCERÍA DE SEDAN #

Type
Sedan     262
SUV        60
Sports     49
Wagon      30
Truck      24
Hybrid      3
Name: count, dtype: int64

In [ ]:
## 2) CROSSTAB, NO SE USAN CAMIONETAS EN EUROPA
crosstab = pd.crosstab(data["Type"], data["Origin"])
crosstab

Origin  Asia  Europe  USA
Type
Hybrid     3       0    0
SUV       25      10   25
Sedan     94      78   90
Sports    17      23    9
Truck      8       0   16
Wagon     11      12    7

In [ ]:
## 3) TIPO DE AJTO CON MENOR PESO
data[["Type", "Weight"]]
data["Weight"].min()  # El menor peso es 1850 ##
data[data["Weight"] == 1850]  ## POR LO QUE  EL TIPO HYBRID ES EL DE MENOR PESO ##

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
150,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110","$17,911",2.0,3.0,73,60,66,1850,95,155

In [ ]:
## 4) MARCAS QUE ELABORAN CARROS HÍBRIDOS, Y TENEMOS QUE 2 HONDA Y 1 YOYOTA ##
data[data["Type"] == "Hybrid"]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
149,Honda,Civic Hybrid 4dr manual (gas/electric),Hybrid,Asia,Front,"$20,140","$18,451",1.4,4.0,93,46,51,2732,103,175
150,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110","$17,911",2.0,3.0,73,60,66,1850,95,155
373,Toyota,Prius 4dr (gas/electric),Hybrid,Asia,Front,"$20,510","$18,926",1.5,4.0,110,59,51,2890,106,175

In [ ]:
## 5) CREAR UNA TABLA CON MODELO MDX
data["Model"].value_counts()
data[data["Model"] == "MDX"]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189

In [ ]:
data["Horsepower"].min()

73

In [ ]:
## 6) ¿CUÁLES SON LOS 3 MODELOS DE AUTO CON MAYOR CABALLOS DE FUERZA ?
data.sort_values(by = "Horsepower", ascending = False).head(3)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
114,Dodge,Viper SRT-10 convertible 2dr,Sports,USA,Rear,"$81,795","$74,451",8.3,10.0,500,12,20,3410,99,176
262,Mercedes-Benz,CL600 2dr,Sedan,Europe,Rear,"$128,420","$119,600",5.5,12.0,493,13,19,4473,114,196
271,Mercedes-Benz,SL600 convertible 2dr,Sports,Europe,Rear,"$126,670","$117,854",5.5,12.0,493,13,19,4429,101,179

In [ ]:
## 7) PARA CADA MARCA ENCONTRAR EL MAYOR VALOR DE RENDIMIENTO DE GASOLINA EN CARRETERA
data.groupby("Make")["MPG_Highway"].max()

Make
Acura            31
Audi             31
BMW              30
Buick            30
Cadillac         26
Chevrolet        37
Chrysler         30
Dodge            36
Ford             36
GMC              25
Honda            66
Hummer           12
Hyundai          34
Infiniti         26
Isuzu            21
Jaguar           28
Jeep             24
Kia              33
Land Rover       21
Lexus            29
Lincoln          26
MINI             37
Mazda            34
Mercedes-Benz    30
Mercury          27
Mitsubishi       31
Nissan           35
Oldsmobile       32
Pontiac          36
Porsche          29
Saab             30
Saturn           35
Scion            38
Subaru           28
Suzuki           31
Toyota           51
Volkswagen       46
Volvo            29
Name: MPG_Highway, dtype: int64

In [ ]:
## 8) CREAR UNA TABLA QUE TENGA LOS REGISTROS MISSING DE CYILINDERS ##
data[data["Cylinders"].isnull()]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
247,Mazda,RX-8 4dr automatic,Sports,Asia,Rear,"$25,700","$23,794",1.3,NaN,197,18,25,3053,106,174
248,Mazda,RX-8 4dr manual,Sports,Asia,Rear,"$27,200","$25,179",1.3,NaN,238,18,24,3029,106,174

In [ ]:
## 9)  Crear una tabla que tenga el registro con el menor gasto de gasolina en ciudad por tipo de vehículo.
data.groupby("Type")["MPG_City"].min()

Type
Hybrid    46
SUV       10
Sedan     12
Sports    12
Truck     13
Wagon     15
Name: MPG_City, dtype: int64